bibop-massive improvements

diff --git a/bibop-massive b/bibop-massive
--- a/bibop-massive
+++ b/bibop-massive
@@ -54,10 +54,19 @@ MERGEABLE_ARGS="enablerepo disablerepo"
 
 ################################################################################
 
-log="bibop-massive.log"
+SEPARATOR="--------------------------------------------------------------------------------"
+YUM_LOG="/var/log/yum.log"
+
+################################################################################
+
+log=""
 dist=""
 
 recipes=""
+cur_recipe=""
+
+pass_count=0
+error_count=0
 
 ################################################################################
 
@@ -94,6 +103,10 @@ main() {
   fi
 
   runTests
+
+  if [[ $error_count -ne 0 ]] ; then
+    exit 1
+  fi
 }
 
 # Check environment
@@ -184,15 +197,35 @@ filterRecipes() {
 # Code: No
 # Echo: No
 runTests() {
-  local recipe
+  local recipe start_ts end_ts
 
-  show "${CL_GREY}----------------------------------------------------------------${CL_NORM}\n"
+  if [[ -z "$log" ]] ; then
+    log="bibop-massive-$(date +'%Y%m%d%H%M').log"
+  fi
+
+  # shellcheck disable=SC2206
+  local recipes_arr=($recipes)
+
+  log "${SEPARATOR//-/▾}"
+  log "Started test suite (recipes: ${#recipes_arr[@]})"
+  log "$SEPARATOR"
+
+  start_ts=$(now)
+
+  show "\n${CL_GREY}${SEPARATOR}${CL_NORM}\n"
 
   for recipe in $recipes ; do
     runTest "$recipe"
   done
 
-  show "${CL_GREY}----------------------------------------------------------------${CL_NORM}\n"
+  show "\n${CL_GREY}${SEPARATOR}${CL_NORM}\n"
+
+  end_ts=$(now)
+  grace_time=$(getGraceTime "$start_ts" "$end_ts")
+
+  show "  ${CL_BOLD}Duration:${CL_NORM} ${grace_time} | ${CL_BOLD}Recipes:${CL_NORM} ${#recipes_arr[@]} | ${CL_BOLD}Passed:${CL_NORM} ${pass_count} | ${CL_BOLD}Errors:${CL_NORM} ${error_count}\n"
+
+  log "Test suite finished (duration: ${grace_time} | pass: ${pass_count} | errors: ${error_count})"
 }
 
 # Run bibop test
@@ -203,7 +236,7 @@ runTests() {
 # Echo: No
 runTest() {
   local recipe="$1"
-  local require_install required_packages packages_installed recipe_name start_ts end_ts grace_time
+  local require_install required_packages packages_installed start_ts end_ts grace_time
 
   required_packages=$(bibop --list-packages "$recipe")
 
@@ -212,15 +245,14 @@ runTest() {
   fi
 
   start_ts=$(now)
-  recipe_name=$(basename "$recipe" | sed 's/.recipe//')
+  cur_recipe=$(basename "$recipe" | sed 's/.recipe//')
 
-  log "-- $recipe_name ----"
-
-  printf "%24s: " "$recipe_name"
+  printf "%24s: " "$cur_recipe"
 
   if [[ -n "$require_install" ]] ; then
-    installPackages "$required_packages"
-   
+    # shellcheck disable=SC2086
+    installPackages $required_packages
+
     # shellcheck disable=SC2181
     if [[ $? -eq 0 ]] ; then
       printStatusBullet $STATUS_OK
@@ -247,6 +279,10 @@ runTest() {
     fi
   fi
 
+  cur_recipe=""
+
+  log "$SEPARATOR"
+
   end_ts=$(now)
   grace_time=$(getGraceTime "$start_ts" "$end_ts")
 
@@ -267,7 +303,7 @@ execRecipe() {
     opts="--error-dir $error_dir"
   fi
 
-  log "Running bibop tests..."
+  log "Running bibop tests…"
 
   # shellcheck disable=SC2086
   bibop -q $opts "$recipe" &>/dev/null
@@ -275,9 +311,11 @@ execRecipe() {
   # shellcheck disable=SC2181
   if [[ $? -eq 0 ]] ; then
     log "Tests successfully passed"
+    (( pass_count++ ))
     return 0
   else
     log "Error while executing tests"
+    (( error_count++ ))
     return 1
   fi
 }
@@ -289,9 +327,9 @@ execRecipe() {
 # Code: Yes
 # Echo: No
 installPackages() {
-  local opts
+  local opts pkg_count
 
-  log "Installing packages: $*"
+  log "Installing packages → $*"
 
   if [[ -n "$enablerepo" ]] ; then
     opts="--enablerepo=$enablerepo"
@@ -301,15 +339,19 @@ installPackages() {
     opts="--disablerepo=$disablerepo"
   fi
 
+  echo -n > $YUM_LOG
+
   # shellcheck disable=SC2086
   yum -q -y $opts install "$@" &>/dev/null
 
   # shellcheck disable=SC2181
   if [[ $? -eq 0 ]] ; then
-    log "Packages successfully installed"
+    pkg_count=$(grep -c 'Installed:' $YUM_LOG)
+    log "Packages successfully installed ($pkg_count installed)"
     return 0
   else
     log "Error while package install"
+    (( error_count++ ))
     return 1
   fi
 }
@@ -319,16 +361,22 @@ installPackages() {
 # Code: Yes
 # Echo: No
 uninstallPackages() {
-  log "Uninstalling packages..."
+  local pkg_count
+
+  log "Uninstalling packages…"
+
+  echo -n > $YUM_LOG
 
   yum -q -y history undo last &>/dev/null
-  
+
   # shellcheck disable=SC2181
   if [[ $? -eq 0 ]] ; then
-    log "Packages successfully uninstalled"
+    pkg_count=$(grep -c 'Erased:' $YUM_LOG)
+    log "Packages successfully uninstalled ($pkg_count uninstalled)"
     return 0
   else
     log "Error while package uninstall"
+    (( error_count++ ))
     return 1
   fi
 }
@@ -403,7 +451,11 @@ hasApp() {
 # Code: No
 # Echo: No
 log() {
-  echo "[$(date +'%Y%m%d %H:%M:%S')] $*" >> "$log"
+  if [[ -n "$cur_recipe" ]] ; then
+    echo "[ $(date +'%Y/%m/%d %H:%M:%S.%3N') ] ($cur_recipe) $*" >> "$log"
+  else
+    echo "[ $(date +'%Y/%m/%d %H:%M:%S.%3N') ] $*" >> "$log"
+  fi
 }
 
 # Show message
