bibop-massive improvements

diff --git a/bibop-massive b/bibop-massive
--- a/bibop-massive
+++ b/bibop-massive
@@ -42,14 +42,14 @@ STATUS_SKIPPED=3
 ################################################################################
 
 APP="bibop-massive"
-VER="1.1.1"
+VER="1.2.0"
 DESC="Utility for mass package testing"
 
 ################################################################################
 
-SUPPORTED_ARGS="error_dir enablerepo disablerepo log !validate !no_colors !help 
+SUPPORTED_OPTS="error_dir enablerepo disablerepo log !validate !no_colors !help 
  !usage !version !ver"
-SHORT_ARGS="e:error_dir V:!validate ER:enablerepo DR:disablerepo l:log 
+SHORT_OPTS="e:error_dir V:!validate ER:enablerepo DR:disablerepo l:log 
  nc:!no_colors h:!help v:!version"
 
 ################################################################################
@@ -105,11 +105,7 @@ main() {
     exit 0
   fi
 
-  if [[ -n "$validate" ]] ; then
-    validateRecipes
-  else
-    runTests
-  fi
+  startProcessing
 
   if [[ $fail_count -ne 0 ]] ; then
     exit 1
@@ -235,6 +231,26 @@ validateRecipes() {
   separator
 }
 
+# Starts recipes processing
+#
+# Code: No
+# Echo: No
+startProcessing() {
+  if [[ $(echo "$recipes" | wc -l) -eq 1 ]] ; then
+    if [[ -n "$validate" ]] ; then
+      validateRecipeVerbose "$recipes"
+    else
+      runTestVerbose "$recipes"
+    fi
+  else
+    if [[ -n "$validate" ]] ; then
+      validateRecipes
+    else
+      runTests
+    fi
+  fi
+}
+
 # Run bibop recipes
 #
 # Code: No
@@ -348,6 +364,64 @@ runTest() {
   show "${CL_DARK} ($grace_time)${CL_NORM}"
 }
 
+# Run bibop test in verbose mode
+#
+# 1: Recipe (String)
+#
+# Code: No
+# Echo: No
+runTestVerbose() {
+  local recipe="$1"
+  local require_install required_packages wrk_dir
+
+  cleanYumCache
+
+  required_packages=$(bibop --list-packages "$recipe")
+
+  if [[ -n "$required_packages" ]] ; then
+    require_install=true
+  fi
+
+  if [[ -n "$require_install" ]] ; then
+    # shellcheck disable=SC2086
+    if ! checkPackagesAvailability $required_packages ; then
+      error "One or more required packages haven't found"
+      exit 1
+    fi
+  fi
+
+  if [[ -n "$require_install" ]] ; then
+    separator
+
+    # shellcheck disable=SC2086
+    installPackagesVerbose $required_packages
+
+    if [[ $? -eq 0 ]] ; then
+      exit 1
+    fi
+  fi
+
+  separator
+
+  execRecipeVerbose "$recipe"
+
+  if [[ $? -eq 0 ]] ; then
+    exit 1
+  fi
+
+  if [[ -n "$require_install" ]] ; then
+    separator
+
+    uninstallPackagesVerbose
+
+    if [[ $? -eq 0 ]] ; then
+      exit 1
+    fi
+  fi
+
+  separator
+}
+
 # Validate recipe
 #
 # 1: Recipe (String)
@@ -424,6 +498,28 @@ execRecipe() {
   fi
 }
 
+# Execute bibop recipe in verbose mode
+#
+# 1: Recipe (String)
+#
+# Code: No
+# Echo: No
+execRecipeVerbose() {
+  local recipe="$1"
+  local opts status wrk_dir
+
+  if [[ -n "$error_dir" ]] ; then
+    opts="--error-dir $error_dir"
+  fi
+
+  wrk_dir=$(dirname "$recipe")
+
+  # shellcheck disable=SC2086
+  bibop -d "$wrk_dir" $opts "$recipe"
+
+  return $?
+}
+
 # Check required packages availability
 #
 # *: List of required packages
@@ -494,6 +590,27 @@ installPackages() {
   fi
 }
 
+# Install required packages in verbose mode
+#
+# *: List of required packages
+#
+# Code: Yes
+# Echo: No
+installPackagesVerbose() {
+  if [[ -n "$enablerepo" ]] ; then
+    opts="--enablerepo=$enablerepo"
+  fi
+
+  if [[ -n "$disablerepo" ]] ; then
+    opts="--disablerepo=$disablerepo"
+  fi
+
+  # shellcheck disable=SC2086
+  LC_ALL=C yum -y $opts install "$@"
+
+  return $?
+}
+
 # Uninstall required packages
 #
 # Code: Yes
@@ -516,6 +633,15 @@ uninstallPackages() {
     (( fail_count++ ))
     return $STATUS_ERROR
   fi
+}
+
+# Uninstall required packages in verbose mode
+#
+# Code: Yes
+# Echo: No
+uninstallPackagesVerbose() {
+  yum -y history undo last
+  return $?
 }
 
 # Clean yum cache
@@ -703,111 +829,114 @@ about() {
   show ""
 }
 
-## ARGUMENTS PARSING 4 #################################################################
+## OPTIONS PARSING 5 ###################################################################
 
-[[ $# -eq 0 ]] && main && exit $?
+if [[ $# -eq 0 ]] ; then
+  main
+  exit $?
+fi
 
-unset arg argn argm argv argt argk
+unset opt optn optm optv optt optk
 
-argv="$*" ; argt=""
+optv="$*" ; optt=""
 
 while [[ -n "$1" ]] ; do
-  if [[ "$1" =~ \  && -n "$argn" ]] ; then
-    declare "$argn=$1"
+  if [[ "$1" =~ \  && -n "$optn" ]] ; then
+    declare "$optn=$1"
 
-    unset argn && shift && continue
+    unset optn && shift && continue
   elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
-    argm=${1:1}
+    optm=${1:1}
 
-    if [[ \ $SHORT_ARGS\  =~ \ $argm:!?([a-zA-Z0-9_]*) ]] ; then
-      arg="${BASH_REMATCH[1]}"
+    if [[ \ $SHORT_OPTS\  =~ \ $optm:!?([a-zA-Z0-9_]*) ]] ; then
+      opt="${BASH_REMATCH[1]}"
     else
-      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
+      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
       shift && continue
     fi
 
-    if [[ -z "$argn" ]] ; then
-      argn=$arg
+    if [[ -z "$optn" ]] ; then
+      optn=$opt
     else
       # shellcheck disable=SC2015
-      [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
-      argn=$arg
+      [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
+      optn=$opt
     fi
 
-    if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
-      declare -F showArgWarn &>/dev/null && showArgWarn "-$argm"
+    if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
+      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
       shift && continue
     fi
 
     if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
-      declare "$argn=true" ; unset argn ; argk=true
+      declare "$optn=true" ; unset optn ; optk=true
     else
-      unset argk
+      unset optk
     fi
 
     shift && continue
   elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
-    arg=${1:2}
+    opt=${1:2}
 
-    if [[ $arg == *=* ]] ; then
-      IFS="=" read -ra arg <<< "$arg"
+    if [[ $opt == *=* ]] ; then
+      IFS="=" read -ra opt <<< "$opt"
 
-      argm="${arg[0]}" ; argm=${argm//-/_}
+      optm="${opt[0]}" ; optm=${optm//-/_}
 
-      if [[ ! $SUPPORTED_ARGS\  =~ $argm\  ]] ; then
-        declare -F showArgWarn &>/dev/null && showArgWarn "--${arg[0]//_/-}"
+      if [[ ! $SUPPORTED_OPTS\  =~ $optm\  ]] ; then
+        declare -F showOptWarn &>/dev/null && showOptWarn "--${opt[0]//_/-}"
         shift && continue
       fi
 
       # shellcheck disable=SC2015
-      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[*]:1:99}" || declare "$argm=${arg[*]:1:99}"
+      [[ -n "${!optm}" && $MERGEABLE_OPTS\  =~ $optm\  ]] && declare "$optm=${!optm} ${opt[*]:1:99}" || declare "$optm=${opt[*]:1:99}"
 
-      unset argm && shift && continue
+      unset optm && shift && continue
     else
       # shellcheck disable=SC2178
-      arg=${arg//-/_}
+      opt=${opt//-/_}
 
-      if [[ -z "$argn" ]] ; then
+      if [[ -z "$optn" ]] ; then
         # shellcheck disable=SC2128
-        argn=$arg
+        optn=$opt
       else
         # shellcheck disable=SC2015
-        [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
+        [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
         # shellcheck disable=SC2128
-        argn=$arg
+        optn=$opt
       fi
 
-      if [[ ! $SUPPORTED_ARGS\  =~ !?$argn\  ]] ; then
-        declare -F showArgWarn &>/dev/null && showArgWarn "--${argn//_/-}"
+      if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
+        declare -F showOptWarn &>/dev/null && showOptWarn "--${optn//_/-}"
         shift && continue
       fi
 
       if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
-        declare "$argn=true" ; unset argn ; argk=true
+        declare "$optn=true" ; unset optn ; optk=true
       else
-        unset argk
+        unset optk
       fi
 
       shift && continue
     fi
   else
-    if [[ -n "$argn" ]] ; then
+    if [[ -n "$optn" ]] ; then
       # shellcheck disable=SC2015
-      [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"
+      [[ -n "${!optn}" && $MERGEABLE_OPTS\  =~ $optn\  ]] && declare "$optn=${!optn} $1" || declare "$optn=$1"
 
-      unset argn && shift && continue
+      unset optn && shift && continue
     fi
   fi
 
-  argt="$argt $1" ; shift
+  optt="$optt $1" ; shift
 
 done
 
-[[ -n "$argn" ]] && declare "$argn=true"
+[[ -n "$optn" ]] && declare "$optn=true"
 
-unset arg argn argm argk
+unset opt optn optm optk
 
 # shellcheck disable=SC2015,SC2086
-[[ -n "$KEEP_ARGS" ]] && main $argv || main ${argt:1}
+[[ -n "$KEEP_OPTS" ]] && main $optv || main ${optt:1}
 
 ########################################################################################
